// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: datanode.proto

#include "datanode.pb.h"
#include "datanode.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace datanode_proto {

static const char* datanodeService_method_names[] = {
  "/datanode_proto.datanodeService/checkalive",
  "/datanode_proto.datanodeService/handleSet",
  "/datanode_proto.datanodeService/handleAppend",
  "/datanode_proto.datanodeService/handleMergeParity",
  "/datanode_proto.datanodeService/handleMergeParityWithRep",
  "/datanode_proto.datanodeService/handleRecovery",
  "/datanode_proto.datanodeService/handleRecoveryBreakdown",
  "/datanode_proto.datanodeService/handleGet",
  "/datanode_proto.datanodeService/handleGetBreakdown",
  "/datanode_proto.datanodeService/handleCordRangeRead",
  "/datanode_proto.datanodeService/handleCordRangeWrite",
  "/datanode_proto.datanodeService/handleCordDeltaBlob",
  "/datanode_proto.datanodeService/handleParityLogAppend",
  "/datanode_proto.datanodeService/handleParityLogStoreD0",
  "/datanode_proto.datanodeService/handleParityLogClearStripe",
  "/datanode_proto.datanodeService/handleParityLogMergeIfFull",
  "/datanode_proto.datanodeService/handleDelete",
};

std::unique_ptr< datanodeService::Stub> datanodeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< datanodeService::Stub> stub(new datanodeService::Stub(channel, options));
  return stub;
}

datanodeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_checkalive_(datanodeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleSet_(datanodeService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleAppend_(datanodeService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleMergeParity_(datanodeService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleMergeParityWithRep_(datanodeService_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleRecovery_(datanodeService_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleRecoveryBreakdown_(datanodeService_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleGet_(datanodeService_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleGetBreakdown_(datanodeService_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleCordRangeRead_(datanodeService_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleCordRangeWrite_(datanodeService_method_names[10], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleCordDeltaBlob_(datanodeService_method_names[11], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleParityLogAppend_(datanodeService_method_names[12], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleParityLogStoreD0_(datanodeService_method_names[13], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleParityLogClearStripe_(datanodeService_method_names[14], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleParityLogMergeIfFull_(datanodeService_method_names[15], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_handleDelete_(datanodeService_method_names[16], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status datanodeService::Stub::checkalive(::grpc::ClientContext* context, const ::datanode_proto::CheckaliveCMD& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::CheckaliveCMD, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_checkalive_, context, request, response);
}

void datanodeService::Stub::async::checkalive(::grpc::ClientContext* context, const ::datanode_proto::CheckaliveCMD* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::CheckaliveCMD, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_checkalive_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::checkalive(::grpc::ClientContext* context, const ::datanode_proto::CheckaliveCMD* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_checkalive_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynccheckaliveRaw(::grpc::ClientContext* context, const ::datanode_proto::CheckaliveCMD& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::CheckaliveCMD, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_checkalive_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynccheckaliveRaw(::grpc::ClientContext* context, const ::datanode_proto::CheckaliveCMD& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccheckaliveRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleSet(::grpc::ClientContext* context, const ::datanode_proto::SetInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::SetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleSet_, context, request, response);
}

void datanodeService::Stub::async::handleSet(::grpc::ClientContext* context, const ::datanode_proto::SetInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::SetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleSet_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleSet(::grpc::ClientContext* context, const ::datanode_proto::SetInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleSet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleSetRaw(::grpc::ClientContext* context, const ::datanode_proto::SetInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::SetInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleSet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleSetRaw(::grpc::ClientContext* context, const ::datanode_proto::SetInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleSetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleAppend(::grpc::ClientContext* context, const ::datanode_proto::AppendInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::AppendInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleAppend_, context, request, response);
}

void datanodeService::Stub::async::handleAppend(::grpc::ClientContext* context, const ::datanode_proto::AppendInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::AppendInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleAppend_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleAppend(::grpc::ClientContext* context, const ::datanode_proto::AppendInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleAppend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleAppendRaw(::grpc::ClientContext* context, const ::datanode_proto::AppendInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::AppendInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleAppend_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleAppendRaw(::grpc::ClientContext* context, const ::datanode_proto::AppendInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleAppendRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleMergeParity(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleMergeParity_, context, request, response);
}

void datanodeService::Stub::async::handleMergeParity(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleMergeParity_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleMergeParity(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleMergeParity_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleMergeParityRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::MergeParityInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleMergeParity_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleMergeParityRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleMergeParityRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleMergeParityWithRep(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleMergeParityWithRep_, context, request, response);
}

void datanodeService::Stub::async::handleMergeParityWithRep(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleMergeParityWithRep_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleMergeParityWithRep(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleMergeParityWithRep_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleMergeParityWithRepRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::MergeParityInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleMergeParityWithRep_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleMergeParityWithRepRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleMergeParityWithRepRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleRecovery(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleRecovery_, context, request, response);
}

void datanodeService::Stub::async::handleRecovery(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleRecovery_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleRecovery(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleRecovery_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleRecoveryRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::MergeParityInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleRecovery_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleRecoveryRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleRecoveryRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleRecoveryBreakdown(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleRecoveryBreakdown_, context, request, response);
}

void datanodeService::Stub::async::handleRecoveryBreakdown(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleRecoveryBreakdown_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleRecoveryBreakdown(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleRecoveryBreakdown_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleRecoveryBreakdownRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::MergeParityInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleRecoveryBreakdown_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleRecoveryBreakdownRaw(::grpc::ClientContext* context, const ::datanode_proto::MergeParityInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleRecoveryBreakdownRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleGet(::grpc::ClientContext* context, const ::datanode_proto::GetInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::GetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleGet_, context, request, response);
}

void datanodeService::Stub::async::handleGet(::grpc::ClientContext* context, const ::datanode_proto::GetInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::GetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleGet_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleGet(::grpc::ClientContext* context, const ::datanode_proto::GetInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleGet_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleGetRaw(::grpc::ClientContext* context, const ::datanode_proto::GetInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::GetInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleGet_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleGetRaw(::grpc::ClientContext* context, const ::datanode_proto::GetInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleGetRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleGetBreakdown(::grpc::ClientContext* context, const ::datanode_proto::GetInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::GetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleGetBreakdown_, context, request, response);
}

void datanodeService::Stub::async::handleGetBreakdown(::grpc::ClientContext* context, const ::datanode_proto::GetInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::GetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleGetBreakdown_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleGetBreakdown(::grpc::ClientContext* context, const ::datanode_proto::GetInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleGetBreakdown_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleGetBreakdownRaw(::grpc::ClientContext* context, const ::datanode_proto::GetInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::GetInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleGetBreakdown_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleGetBreakdownRaw(::grpc::ClientContext* context, const ::datanode_proto::GetInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleGetBreakdownRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleCordRangeRead(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::CordRangeRWInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleCordRangeRead_, context, request, response);
}

void datanodeService::Stub::async::handleCordRangeRead(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::CordRangeRWInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleCordRangeRead_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleCordRangeRead(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleCordRangeRead_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleCordRangeReadRaw(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::CordRangeRWInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleCordRangeRead_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleCordRangeReadRaw(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleCordRangeReadRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleCordRangeWrite(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::CordRangeRWInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleCordRangeWrite_, context, request, response);
}

void datanodeService::Stub::async::handleCordRangeWrite(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::CordRangeRWInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleCordRangeWrite_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleCordRangeWrite(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleCordRangeWrite_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleCordRangeWriteRaw(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::CordRangeRWInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleCordRangeWrite_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleCordRangeWriteRaw(::grpc::ClientContext* context, const ::datanode_proto::CordRangeRWInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleCordRangeWriteRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleCordDeltaBlob(::grpc::ClientContext* context, const ::datanode_proto::CordDeltaBlobInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::CordDeltaBlobInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleCordDeltaBlob_, context, request, response);
}

void datanodeService::Stub::async::handleCordDeltaBlob(::grpc::ClientContext* context, const ::datanode_proto::CordDeltaBlobInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::CordDeltaBlobInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleCordDeltaBlob_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleCordDeltaBlob(::grpc::ClientContext* context, const ::datanode_proto::CordDeltaBlobInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleCordDeltaBlob_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleCordDeltaBlobRaw(::grpc::ClientContext* context, const ::datanode_proto::CordDeltaBlobInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::CordDeltaBlobInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleCordDeltaBlob_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleCordDeltaBlobRaw(::grpc::ClientContext* context, const ::datanode_proto::CordDeltaBlobInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleCordDeltaBlobRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleParityLogAppend(::grpc::ClientContext* context, const ::datanode_proto::ParityLogAppendInfo& request, ::datanode_proto::ParityLogAppendReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::ParityLogAppendInfo, ::datanode_proto::ParityLogAppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleParityLogAppend_, context, request, response);
}

void datanodeService::Stub::async::handleParityLogAppend(::grpc::ClientContext* context, const ::datanode_proto::ParityLogAppendInfo* request, ::datanode_proto::ParityLogAppendReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::ParityLogAppendInfo, ::datanode_proto::ParityLogAppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogAppend_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleParityLogAppend(::grpc::ClientContext* context, const ::datanode_proto::ParityLogAppendInfo* request, ::datanode_proto::ParityLogAppendReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogAppend_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::ParityLogAppendReply>* datanodeService::Stub::PrepareAsynchandleParityLogAppendRaw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogAppendInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::ParityLogAppendReply, ::datanode_proto::ParityLogAppendInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleParityLogAppend_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::ParityLogAppendReply>* datanodeService::Stub::AsynchandleParityLogAppendRaw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogAppendInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleParityLogAppendRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleParityLogStoreD0(::grpc::ClientContext* context, const ::datanode_proto::ParityLogStoreD0Info& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::ParityLogStoreD0Info, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleParityLogStoreD0_, context, request, response);
}

void datanodeService::Stub::async::handleParityLogStoreD0(::grpc::ClientContext* context, const ::datanode_proto::ParityLogStoreD0Info* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::ParityLogStoreD0Info, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogStoreD0_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleParityLogStoreD0(::grpc::ClientContext* context, const ::datanode_proto::ParityLogStoreD0Info* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogStoreD0_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleParityLogStoreD0Raw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogStoreD0Info& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::ParityLogStoreD0Info, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleParityLogStoreD0_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleParityLogStoreD0Raw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogStoreD0Info& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleParityLogStoreD0Raw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleParityLogClearStripe(::grpc::ClientContext* context, const ::datanode_proto::ParityLogClearStripeInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::ParityLogClearStripeInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleParityLogClearStripe_, context, request, response);
}

void datanodeService::Stub::async::handleParityLogClearStripe(::grpc::ClientContext* context, const ::datanode_proto::ParityLogClearStripeInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::ParityLogClearStripeInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogClearStripe_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleParityLogClearStripe(::grpc::ClientContext* context, const ::datanode_proto::ParityLogClearStripeInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogClearStripe_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleParityLogClearStripeRaw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogClearStripeInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::ParityLogClearStripeInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleParityLogClearStripe_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleParityLogClearStripeRaw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogClearStripeInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleParityLogClearStripeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleParityLogMergeIfFull(::grpc::ClientContext* context, const ::datanode_proto::ParityLogMergeIfFullInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::ParityLogMergeIfFullInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleParityLogMergeIfFull_, context, request, response);
}

void datanodeService::Stub::async::handleParityLogMergeIfFull(::grpc::ClientContext* context, const ::datanode_proto::ParityLogMergeIfFullInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::ParityLogMergeIfFullInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogMergeIfFull_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleParityLogMergeIfFull(::grpc::ClientContext* context, const ::datanode_proto::ParityLogMergeIfFullInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleParityLogMergeIfFull_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleParityLogMergeIfFullRaw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogMergeIfFullInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::ParityLogMergeIfFullInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleParityLogMergeIfFull_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleParityLogMergeIfFullRaw(::grpc::ClientContext* context, const ::datanode_proto::ParityLogMergeIfFullInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleParityLogMergeIfFullRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status datanodeService::Stub::handleDelete(::grpc::ClientContext* context, const ::datanode_proto::DelInfo& request, ::datanode_proto::RequestResult* response) {
  return ::grpc::internal::BlockingUnaryCall< ::datanode_proto::DelInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_handleDelete_, context, request, response);
}

void datanodeService::Stub::async::handleDelete(::grpc::ClientContext* context, const ::datanode_proto::DelInfo* request, ::datanode_proto::RequestResult* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::datanode_proto::DelInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleDelete_, context, request, response, std::move(f));
}

void datanodeService::Stub::async::handleDelete(::grpc::ClientContext* context, const ::datanode_proto::DelInfo* request, ::datanode_proto::RequestResult* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_handleDelete_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::PrepareAsynchandleDeleteRaw(::grpc::ClientContext* context, const ::datanode_proto::DelInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::datanode_proto::RequestResult, ::datanode_proto::DelInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_handleDelete_, context, request);
}

::grpc::ClientAsyncResponseReader< ::datanode_proto::RequestResult>* datanodeService::Stub::AsynchandleDeleteRaw(::grpc::ClientContext* context, const ::datanode_proto::DelInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynchandleDeleteRaw(context, request, cq);
  result->StartCall();
  return result;
}

datanodeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::CheckaliveCMD, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::CheckaliveCMD* req,
             ::datanode_proto::RequestResult* resp) {
               return service->checkalive(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::SetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::SetInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleSet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::AppendInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::AppendInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleAppend(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::MergeParityInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleMergeParity(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::MergeParityInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleMergeParityWithRep(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::MergeParityInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleRecovery(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::MergeParityInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::MergeParityInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleRecoveryBreakdown(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::GetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::GetInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleGet(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::GetInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::GetInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleGetBreakdown(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::CordRangeRWInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::CordRangeRWInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleCordRangeRead(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::CordRangeRWInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::CordRangeRWInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleCordRangeWrite(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::CordDeltaBlobInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::CordDeltaBlobInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleCordDeltaBlob(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[12],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::ParityLogAppendInfo, ::datanode_proto::ParityLogAppendReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::ParityLogAppendInfo* req,
             ::datanode_proto::ParityLogAppendReply* resp) {
               return service->handleParityLogAppend(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[13],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::ParityLogStoreD0Info, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::ParityLogStoreD0Info* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleParityLogStoreD0(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[14],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::ParityLogClearStripeInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::ParityLogClearStripeInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleParityLogClearStripe(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[15],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::ParityLogMergeIfFullInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::ParityLogMergeIfFullInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleParityLogMergeIfFull(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      datanodeService_method_names[16],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< datanodeService::Service, ::datanode_proto::DelInfo, ::datanode_proto::RequestResult, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](datanodeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::datanode_proto::DelInfo* req,
             ::datanode_proto::RequestResult* resp) {
               return service->handleDelete(ctx, req, resp);
             }, this)));
}

datanodeService::Service::~Service() {
}

::grpc::Status datanodeService::Service::checkalive(::grpc::ServerContext* context, const ::datanode_proto::CheckaliveCMD* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleSet(::grpc::ServerContext* context, const ::datanode_proto::SetInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleAppend(::grpc::ServerContext* context, const ::datanode_proto::AppendInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleMergeParity(::grpc::ServerContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleMergeParityWithRep(::grpc::ServerContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleRecovery(::grpc::ServerContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleRecoveryBreakdown(::grpc::ServerContext* context, const ::datanode_proto::MergeParityInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleGet(::grpc::ServerContext* context, const ::datanode_proto::GetInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleGetBreakdown(::grpc::ServerContext* context, const ::datanode_proto::GetInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleCordRangeRead(::grpc::ServerContext* context, const ::datanode_proto::CordRangeRWInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleCordRangeWrite(::grpc::ServerContext* context, const ::datanode_proto::CordRangeRWInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleCordDeltaBlob(::grpc::ServerContext* context, const ::datanode_proto::CordDeltaBlobInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleParityLogAppend(::grpc::ServerContext* context, const ::datanode_proto::ParityLogAppendInfo* request, ::datanode_proto::ParityLogAppendReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleParityLogStoreD0(::grpc::ServerContext* context, const ::datanode_proto::ParityLogStoreD0Info* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleParityLogClearStripe(::grpc::ServerContext* context, const ::datanode_proto::ParityLogClearStripeInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleParityLogMergeIfFull(::grpc::ServerContext* context, const ::datanode_proto::ParityLogMergeIfFullInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status datanodeService::Service::handleDelete(::grpc::ServerContext* context, const ::datanode_proto::DelInfo* request, ::datanode_proto::RequestResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace datanode_proto

