#!/usr/bin/env python3
"""
Sort a column of IPs and rewrite cluster deployment configs.

Role assignment (after numeric sort), default 6 clusters × 8 datanodes:
  [0]       client
  [1]       coordinator
  per cluster c in 0..N-1:
    [2+c*9]       proxy (port 50405+c)
    [3+c*9 .. 10+c*9]  8 datanodes (ports 17600+8*c ..)

Updates: hosts, proxy_hosts, datanode_hosts, clusterInformation.xml,
parameterConfiguration.xml, limit_bw_matrix.sh, unlimit_bw_matrix.sh,
small_tools/generator_sh.py, project/run_cpp/main_client.cpp

Usage:
  python3 apply_sorted_ips.py ip_list.txt
  python3 apply_sorted_ips.py -   # stdin, one IP per line
  sort -V ip_list.txt | python3 apply_sorted_ips.py -
"""

from __future__ import print_function

import argparse
import ipaddress
import os
import re
import sys

try:
    from xml.etree import ElementTree as ET
except ImportError:
    from elementtree import ElementTree as ET

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

CLUSTER_NUM = int(os.environ.get("CLUSTER_NUM", "6"))
DATANODES_PER_CLUSTER = int(os.environ.get("DATANODES_PER_CLUSTER", "8"))
PROXY_PORT_BASE = int(os.environ.get("PROXY_PORT_BASE", "50405"))
DATANODE_PORT_START = int(os.environ.get("DATANODE_PORT_START", "17600"))

CLUSTER_LABELS = ["TYO", "MEL", "SG", "SEO", "JAK", "HK"]

PATHS = {
    "hosts": os.path.join(ROOT, "hosts"),
    "proxy_hosts": os.path.join(ROOT, "proxy_hosts"),
    "datanode_hosts": os.path.join(ROOT, "datanode_hosts"),
    "cluster_xml": os.path.join(ROOT, "project", "config", "clusterInformation.xml"),
    "param_xml": os.path.join(ROOT, "project", "config", "parameterConfiguration.xml"),
    "limit_bw": os.path.join(ROOT, "limit_bw_matrix.sh"),
    "unlimit_bw": os.path.join(ROOT, "unlimit_bw_matrix.sh"),
    "generator_py": os.path.join(ROOT, "small_tools", "generator_sh.py"),
    "main_client": os.path.join(ROOT, "project", "run_cpp", "main_client.cpp"),
    "start_coordinator": os.path.join(ROOT, "start_coordinator.sh"),
}


def expected_ip_count():
    return 2 + CLUSTER_NUM * (1 + DATANODES_PER_CLUSTER)


def parse_ip_lines(lines):
    ips = []
    seen = set()
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        token = line.split()[0].strip()
        try:
            ipaddress.ip_address(token)
        except ValueError as exc:
            raise ValueError("invalid IP: %r (%s)" % (token, exc))
        if token in seen:
            raise ValueError("duplicate IP: %s" % token)
        seen.add(token)
        ips.append(token)
    return ips


def sort_ips(ips):
    return sorted(ips, key=lambda x: ipaddress.ip_address(x))


def assign_roles(sorted_ips):
    need = expected_ip_count()
    if len(sorted_ips) != need:
        raise ValueError(
            "need exactly %d IPs (1 client + 1 coordinator + %d clusters × "
            "(1 proxy + %d datanodes)), got %d"
            % (need, CLUSTER_NUM, DATANODES_PER_CLUSTER, len(sorted_ips))
        )

    client_ip = sorted_ips[0]
    coordinator_ip = sorted_ips[1]
    clusters = []
    idx = 2
    for cid in range(CLUSTER_NUM):
        proxy_ip = sorted_ips[idx]
        idx += 1
        dn_ips = sorted_ips[idx : idx + DATANODES_PER_CLUSTER]
        idx += DATANODES_PER_CLUSTER
        port0 = DATANODE_PORT_START + cid * DATANODES_PER_CLUSTER
        clusters.append(
            {
                "id": cid,
                "proxy_ip": proxy_ip,
                "proxy_port": PROXY_PORT_BASE + cid,
                "datanode_ips": dn_ips,
                "datanode_ports": [port0 + j for j in range(DATANODES_PER_CLUSTER)],
            }
        )
    return client_ip, coordinator_ip, clusters


def write_lines(path, lines):
    with open(path, "w") as f:
        for line in lines:
            f.write(line + "\n")
    print("  wrote %s (%d lines)" % (path, len(lines)))


def write_cluster_xml(path, client_ip, coordinator_ip, clusters):
    lines = [
        "<?xml version='1.0' encoding='utf-8'?>",
        "<!-- auto-generated by apply_sorted_ips.py -->",
        "<!-- client=%s coordinator=%s clusters=%d datanodes/cluster=%d -->"
        % (client_ip, coordinator_ip, CLUSTER_NUM, DATANODES_PER_CLUSTER),
        "<clusters>",
    ]
    for i, c in enumerate(clusters):
        lines.append('\t<cluster id="%d" proxy="%s:%d">' % (c["id"], c["proxy_ip"], c["proxy_port"]))
        lines.append("\t\t<datanodes>")
        for j, (ip, port) in enumerate(zip(c["datanode_ips"], c["datanode_ports"])):
            lines.append('\t\t\t<datanode uri="%s:%d" />' % (ip, port))
        lines.append("\t\t</datanodes>")
        lines.append("\t</cluster>")
    lines.append("</clusters>")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))
    print("  wrote %s" % path)


def patch_coordinator_ip(path, coordinator_ip):
    with open(path, "r") as f:
        text = f.read()
    new_text, n = re.subn(
        r"(<CoordinatorIP>)[^<]+(</CoordinatorIP>)",
        r"\g<1>%s\2" % coordinator_ip,
        text,
        count=1,
    )
    if n != 1:
        raise RuntimeError("CoordinatorIP not found in %s" % path)
    with open(path, "w") as f:
        f.write(new_text)
    print("  patched CoordinatorIP -> %s in %s" % (coordinator_ip, path))


def patch_bash_ip_array(path, var_name, ip_lines):
    """Replace VAR=( ... ) block; ip_lines are full inner lines including quotes."""
    with open(path, "r") as f:
        text = f.read()
    block = var_name + "=(\n" + "\n".join(ip_lines) + "\n)"
    pattern = re.compile(
        r"%s=\(\n(?:.*?\n)*?\)" % re.escape(var_name), re.MULTILINE
    )
    new_text, n = pattern.subn(block, text, count=1)
    if n != 1:
        raise RuntimeError("%s=(...) not found in %s" % (var_name, path))
    with open(path, "w") as f:
        f.write(new_text)
    print("  patched %s in %s" % (var_name, path))


def patch_limit_scripts(client_ip, coordinator_ip, clusters):
    skip_lines = ['  "%s"' % client_ip, '  "%s"' % coordinator_ip]
    cluster_lines = []
    for c in clusters:
        label = CLUSTER_LABELS[c["id"]] if c["id"] < len(CLUSTER_LABELS) else "c%d" % c["id"]
        cluster_lines.append(
            '  "%s"   # %d: %s  cluster %d proxy'
            % (c["proxy_ip"], c["id"], label, c["id"])
        )
    for path in (PATHS["limit_bw"], PATHS["unlimit_bw"]):
        patch_bash_ip_array(path, "SKIP_BW_LIMIT_IPS", skip_lines)
        patch_bash_ip_array(path, "CLUSTER_IPS", cluster_lines)


def patch_generator_py(path, coordinator_ip, clusters):
    with open(path, "r") as f:
        text = f.read()

    proxy_entries = []
    for c in clusters:
        proxy_entries.append('    ["%s", %d],' % (c["proxy_ip"], c["proxy_port"]))

    proxy_block = "proxy_ip_list = [\n" + "\n".join(proxy_entries) + "\n]"
    text, n = re.subn(
        r"proxy_ip_list = \[\n(?:.*?\n)*?\]",
        proxy_block,
        text,
        count=1,
    )
    if n != 1:
        raise RuntimeError("proxy_ip_list not found in %s" % path)

    text, n2 = re.subn(
        r'^coordinator_ip = "[^"]*"',
        'coordinator_ip = "%s"' % coordinator_ip,
        text,
        count=1,
        flags=re.MULTILINE,
    )
    if n2 != 1:
        raise RuntimeError("coordinator_ip not found in %s" % path)

    with open(path, "w") as f:
        f.write(text)
    print("  patched generator_sh.py (proxy_ip_list + coordinator_ip)")


def patch_start_coordinator(path, coordinator_ip):
    with open(path, "r") as f:
        text = f.read()
    new_text, n = re.subn(
        r'pdsh -R ssh -w [^ ]+ -l',
        'pdsh -R ssh -w %s -l' % coordinator_ip,
        text,
        count=1,
    )
    if n != 1:
        # start_coordinator.sh may already read CoordinatorIP from parameterConfiguration.xml
        if "parameterConfiguration.xml" in text or "COORDINATOR_IP" in text:
            print("  start_coordinator.sh already reads CoordinatorIP dynamically; skipped")
            return
        raise RuntimeError("pdsh coordinator target not found in %s" % path)
    with open(path, "w") as f:
        f.write(new_text)
    print("  patched start_coordinator.sh -> %s" % coordinator_ip)


def patch_main_client(path, client_ip):
    with open(path, "r") as f:
        text = f.read()
    new_text, n = re.subn(
        r'std::string client_ip = "[^"]*";',
        'std::string client_ip = "%s";' % client_ip,
        text,
        count=1,
    )
    if n != 1:
        raise RuntimeError("client_ip not found in %s" % path)
    with open(path, "w") as f:
        f.write(new_text)
    print("  patched client_ip -> %s in main_client.cpp" % client_ip)


def apply(sorted_ips, dry_run=False):
    client_ip, coordinator_ip, clusters = assign_roles(sorted_ips)
    proxy_ips = [c["proxy_ip"] for c in clusters]
    datanode_ips = []
    for c in clusters:
        datanode_ips.extend(c["datanode_ips"])

    print("Sorted %d IPs -> roles:" % len(sorted_ips))
    print("  client=%s coordinator=%s" % (client_ip, coordinator_ip))
    for c in clusters:
        label = CLUSTER_LABELS[c["id"]] if c["id"] < len(CLUSTER_LABELS) else "?"
        print(
            "  cluster %d (%s): proxy=%s:%d datanodes=%s"
            % (c["id"], label, c["proxy_ip"], c["proxy_port"], ",".join(c["datanode_ips"]))
        )

    if dry_run:
        print("Dry run; no files written.")
        return

    write_lines(PATHS["hosts"], sorted_ips)
    write_lines(PATHS["proxy_hosts"], proxy_ips)
    write_lines(PATHS["datanode_hosts"], datanode_ips)
    write_cluster_xml(PATHS["cluster_xml"], client_ip, coordinator_ip, clusters)
    patch_coordinator_ip(PATHS["param_xml"], coordinator_ip)
    patch_limit_scripts(client_ip, coordinator_ip, clusters)
    patch_generator_py(PATHS["generator_py"], coordinator_ip, clusters)
    patch_main_client(PATHS["main_client"], client_ip)
    if os.path.isfile(PATHS["start_coordinator"]):
        patch_start_coordinator(PATHS["start_coordinator"], coordinator_ip)
    print("Done.")


def main():
    parser = argparse.ArgumentParser(description="Sort IPs and update cluster configs.")
    parser.add_argument(
        "ip_file",
        nargs="?",
        default="-",
        help="file with one IP per line, or '-' for stdin",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print mapping only, do not write files",
    )
    args = parser.parse_args()

    if args.ip_file == "-":
        lines = sys.stdin.readlines()
    else:
        with open(args.ip_file, "r") as f:
            lines = f.readlines()

    ips = parse_ip_lines(lines)
    sorted_ips = sort_ips(ips)
    apply(sorted_ips, dry_run=args.dry_run)


if __name__ == "__main__":
    main()